[profile.default]

src = "contracts"

lib = ["lib", "node_modules"]

optimizer = true
optimizer-runs = 200

via-ir = true

remappings = [
	'lib/ens-contracts:@openzeppelin/contracts=lib/openzeppelin-contracts-v4.9/contracts/',
	'@ensdomains/ens-contracts=lib/ens-contracts/',
	'@ensdomains/buffer=lib/buffer',

	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',

	'@unruggable/evmgateway=node_modules/@unruggable/evmgateway/'
]
